### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by zetapin** [Vuurvos1/twitchTTS#4]
tts don work. ¿some problem?

**Comment by Vuurvos1** [comment]
Hey, thanks for leaving this issue. I did a bit of investigating why it broke, it seems there is an issue with the Streamlabs API used for converting the text into audio (maybe they took the API down?). So sadly no easy fix by the looks of it

**Comment by zetapin** [comment]
If you find a solution, please let me know

**Comment by Vuurvos1** [comment]
So apparently the streamlabs API slightly changes and you now need to send a referer header while calling the API. So everything should be working again. If you still have issues, please leave a new issue
